name: MCBasics
version: 1.0.0
main: dev.luca.mcbasics.MCBasics
api-version: 1.21
description: Essential commands plugin for Minecraft Paper 1.21.11

commands:
  help:
    description: Show the help menu
    usage: /help [page]
  vanish:
    description: Toggle vanish mode
    usage: /vanish [player]
  gm:
    description: Change gamemode
    usage: /gm <0/1/2/3> [player]
  gmc:
    description: Change to creative mode
    usage: /gmc [player]
  gms:
    description: Change to survival mode
    usage: /gms [player]
  gma:
    description: Change to adventure mode
    usage: /gma [player]
  gmsp:
    description: Change to spectator mode
    usage: /gmsp [player]
  invsee:
    description: View another player's inventory
    usage: /invsee <player>
  tphere:
    description: Teleport a player to you
    usage: /tphere <player>
  feed:
    description: Fill your hunger bar
    usage: /feed [player]
  heal:
    description: Heal yourself or another player
    usage: /heal [player]
  speed:
    description: Set walking speed
    usage: /speed <1-10> [player]
  fly:
    description: Toggle flight
    usage: /fly [player]
  unsafeenchant:
    description: Add any enchantment at any level
    usage: /unsafeenchant <enchantment> <level> [player]

permissions:
  mcbasics.*:
    description: All MCBasics permissions
    children:
      mcbasics.vanish: true
      mcbasics.vanish.see: true
      mcbasics.gm: true
      mcbasics.gm.others: true
      mcbasics.invsee: true
      mcbasics.tphere: true
      mcbasics.feed: true
      mcbasics.feed.others: true
      mcbasics.heal: true
      mcbasics.heal.others: true
      mcbasics.speed: true
      mcbasics.speed.others: true
      mcbasics.fly: true
      mcbasics.fly.others: true
      mcbasics.unsafeenchant: true
      mcbasics.help: true

  mcbasics.vanish:
    description: Allows use of /vanish
    default: op
  mcbasics.vanish.see:
    description: Allows seeing vanished players
    default: op
  mcbasics.gm:
    description: Allows use of /gm
    default: op
  mcbasics.gm.others:
    description: Allows changing other players' gamemode
    default: op
  mcbasics.invsee:
    description: Allows use of /invsee
    default: op
  mcbasics.tphere:
    description: Allows use of /tphere
    default: op
  mcbasics.feed:
    description: Allows use of /feed
    default: true
  mcbasics.feed.others:
    description: Allows feeding other players
    default: op
  mcbasics.heal:
    description: Allows use of /heal
    default: true
  mcbasics.heal.others:
    description: Allows healing other players
    default: op
  mcbasics.speed:
    description: Allows use of /speed
    default: true
  mcbasics.speed.others:
    description: Allows changing other players' speed
    default: op
  mcbasics.fly:
    description: Allows use of /fly
    default: true
  mcbasics.fly.others:
    description: Allows toggling flight for other players
    default: op
  mcbasics.unsafeenchant:
    description: Allows use of /unsafeenchant
    default: op
  mcbasics.help:
    description: Allows use of /help
    default: true
